name: Build and deploy ASP.Net Core app to Azure Web App - UPB-Certi-Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: |
          dotnet build --configuration Release FinalPractice/FinalPractice.csproj
          dotnet build --configuration Release CoreLogic/CoreLogic.csproj

      - name: dotnet publish FinalPractice
        run: dotnet publish --configuration Release --output ${{github.workspace}}/FinalPracticePublish FinalPractice/FinalPractice.csproj

      - name: dotnet publish CoreLogic
        run: dotnet publish --configuration Release --output ${{github.workspace}}/CoreLogicPublish CoreLogic/CoreLogic.csproj

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app
          path: |
            ${{github.workspace}}/FinalPracticePublish
            ${{github.workspace}}/CoreLogicPublish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: dotnet-app
          path: ${{github.workspace}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'UPB-Certi-Test'
          slot-name: 'Production'
          publish-profile: ${{secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D40A2C408D8D4FC6A1447A74A9E7AEB1}}
          package: ${{github.workspace}}/FinalPracticePublish
